### ISSUE TITLE
The 'changed' argument of the action function does not contain fields that had no initial value

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#13]
This seems to be a design choice (cf. [this comment](https://github.com/meteortemplates/forms/blob/master/templates:forms.coffee#L101)).
However, a standard use case is that you have an optional field in your collection, initially undefined. In the update form, you enter a value for this field. Then you have to update the collection with this new value. If the field is not present in `changed`, you still have to scan `this`, and `changed` is useless...

**Comment by jonjamz** [comment]
Ah--good catch. That totally makes sense.

**Comment by jonjamz** [comment]
This should solve it.

**Comment by steph643** [comment]
Fix works great.

**Comment by steph643** [comment]
Remaining issue: `changed` still does not work if the form was initialized with no data argument (it works well if there was an empty data argument).

```
    {{! Init the form with no data argument}}
    {{#myFormBlock schema=schema action=action}}
        {{> myInput field='testField'}}
    {{/myFormBlock}}
```
In that case, if user enters something in the input, `changed` will be empty instead of containing the new value.

**Comment by jonjamz** [comment]
I did it this way on purpose because without initial data nothing will have "changed" and the fields with values would all be in "this" in the action function. That way you can use "if (_.isEmpty(changed)) { ...insert... }" to see if it's an update or an insert.

**Comment by steph643** [comment]
Ok, it makes sense.
If explained in the doc, an empty object is fine (but I think `undefined` would be even better).
